--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/antbag-dev/TrashCommand
build-by-default: true
branches:
- main
projects:
  TrashCommand:
    path: ""
    icon: 'bin.png'
    libs:
      - src: Muqsit/InvMenu/InvMenu
        version: ^4.6.1
        branch: "pm5"
...
