name: TrashCommand
author: antbag
version: 0.0.1
api: 5.0.0
main: antbag\TrashCommand\Main

commands:
  trash:
    description: Open the Garbage Menu
    permission: trash.command.use
    
permissions:
  trash.command.use:
    description: permission to access the Garbage Menu
    default: true
